// ── Question Bank (~500 questions) ──
// Organized by category. Each question captures personality, voice, reasoning.

export interface Question {
    id: number;
    category: string;
    text: string;
    depth: 'basic' | 'deep' | 'expert';
}

const raw: Record<string, string[]> = {
    personalidad: [
        '¿Cómo te describirías en tres palabras?',
        '¿Qué es lo primero que la gente nota de ti?',
        '¿Eres más introvertido o extrovertido?',
        '¿Qué te hace reír sin falta?',
        '¿Cuál es tu mayor fortaleza como persona?',
        '¿Y tu mayor debilidad?',
        '¿Cómo reaccionas cuando algo te frustra?',
        '¿Qué te da energía durante el día?',
        '¿Qué te quita la energía?',
        '¿Te consideras optimista, pesimista o realista?',
        '¿Cómo manejas la presión?',
        '¿Eres más de planificar o de improvisar?',
        '¿Qué haces cuando estás solo y aburrido?',
        '¿Qué tipo de humor tienes?',
        '¿Te cuesta pedir ayuda?',
        '¿Cómo reaccionas ante los cumplidos?',
        '¿Qué te hace sentir orgulloso de ti mismo?',
        '¿Eres competitivo?',
        '¿Prefieres liderar o seguir?',
        '¿Cómo manejas las críticas?',
        '¿Qué te molesta de otras personas?',
        '¿Te consideras paciente?',
        '¿Eres rencoroso o perdonas fácil?',
        '¿Cómo celebras tus logros?',
        '¿Qué te pone nervioso?',
        '¿Qué hábito te gustaría cambiar?',
        '¿Te consideras creativo?',
        '¿Qué rol tomas en un grupo de amigos?',
        '¿Prefieres las mañanas o las noches?',
        '¿Cómo describes tu estilo personal?',
        '¿Qué te hace diferente a los demás?',
        '¿Cuál es tu forma de mostrar cariño?',
        '¿Eres más racional o emocional?',
        '¿Cómo te ven tus amigos más cercanos?',
        '¿Te adaptas fácil a los cambios?',
        '¿Qué valor es innegociable para ti?',
        '¿Prefieres la rutina o la aventura?',
        '¿Cómo actúas cuando estás triste?',
        '¿Qué te hace sentir en paz?',
        '¿Eres de los que hablan mucho o escuchan más?',
        '¿Cuál es tu forma de resolver problemas?',
        '¿Qué tan importante es la aprobación de otros para ti?',
        '¿Prefieres estar acompañado o solo?',
        '¿Cómo reaccionas ante lo inesperado?',
        '¿Confías fácilmente en las personas?',
        '¿Qué te inspira a ser mejor persona?',
        '¿Te gusta tener el control de las situaciones?',
        '¿Cómo describes tu temperamento?',
        '¿Qué admiras en otras personas?',
        '¿Qué detestas en otras personas?',
    ],
    valores: [
        '¿Qué principio guía tu vida?',
        '¿Qué significa para ti la lealtad?',
        '¿Qué es más importante: ser honesto o ser amable?',
        '¿Qué harías si encontraras una billetera con dinero?',
        '¿Crees que el fin justifica los medios?',
        '¿Qué tan importante es la familia para ti?',
        '¿Qué sacrificarías por alguien que amas?',
        '¿Cuál es tu posición sobre las mentiras piadosas?',
        '¿Qué significa el éxito para ti?',
        '¿Qué significa la felicidad para ti?',
        '¿Prefieres justicia o misericordia?',
        '¿Crees en las segundas oportunidades?',
        '¿Qué tan importante es el dinero?',
        '¿Qué enseñanza le darías a un hijo?',
        '¿Crees que la gente puede cambiar?',
        '¿Qué rol tiene la religión o espiritualidad en tu vida?',
        '¿Qué opinas del perdón?',
        '¿Cuál es tu responsabilidad hacia los demás?',
        '¿Qué valor quieres que te recuerden?',
        '¿Prefieres la verdad incómoda o la ignorancia feliz?',
        '¿Qué opinas de la gratitud?',
        '¿Crees en el karma?',
        '¿Qué significa ser "buena persona"?',
        '¿Qué harías con poder ilimitado?',
        '¿Qué causa social te importa más?',
        '¿Cómo defines la integridad?',
        '¿Qué opinas sobre la privacidad?',
        '¿Prefieres dar o recibir?',
        '¿Qué tan importante es cumplir las promesas?',
        '¿Cómo decides qué es correcto y qué no?',
        '¿Qué opinas de la competencia vs la colaboración?',
        '¿Qué significa el respeto para ti?',
        '¿Crees que todos merecen las mismas oportunidades?',
        '¿Qué tan importante es la educación?',
        '¿Qué opinas sobre la libertad individual?',
        '¿Cuál es tu deber más importante?',
        '¿Qué piensas del consumismo?',
        '¿Crees que la humildad es una virtud?',
        '¿Qué opinas de la ambición?',
        '¿Qué legado quieres dejar?',
        '¿Crees en la meritocracia?',
        '¿Qué tan importante es la coherencia entre lo que dices y haces?',
        '¿Qué opinas de la venganza?',
        '¿Prefieres seguridad o libertad?',
        '¿Qué significa la dignidad?',
        '¿Crees que hay verdades absolutas?',
        '¿Qué piensas del sacrificio personal?',
        '¿Qué opinas de la solidaridad?',
        '¿Qué tan importante es la autenticidad?',
        '¿Cuál es la diferencia entre querer y necesitar?',
    ],
    recuerdos: [
        '¿Cuál es tu recuerdo más feliz de la infancia?',
        '¿Cuál es el mejor viaje que has hecho?',
        '¿Qué momento de tu vida cambió todo?',
        '¿Cuál ha sido tu logro más significativo?',
        '¿Hay algo que desearías haber hecho diferente?',
        '¿Cuál fue tu primer trabajo?',
        '¿Cuál es tu recuerdo favorito con tu familia?',
        '¿Qué consejo recibiste que nunca olvidaste?',
        '¿Cuál fue el día más difícil de tu vida?',
        '¿Recuerdas tu primera amistad verdadera?',
        '¿Cuál fue tu momento más vergonzoso?',
        '¿Qué evento histórico te marcó?',
        '¿Cuál es tu recuerdo favorito de la escuela?',
        '¿Cuál fue tu primer gran susto?',
        '¿Recuerdas el primer libro que te impactó?',
        '¿Cuál fue tu primera desilusión?',
        '¿Qué navidad o festividad recuerdas con más cariño?',
        '¿Cuál fue tu primer logro del que te sentiste orgulloso?',
        '¿Hay un olor que te transporte a un recuerdo?',
        '¿Cuál fue la mejor sorpresa que recibiste?',
        '¿Recuerdas la primera vez que cocinaste algo?',
        '¿Cuál es el mejor regalo que has recibido?',
        '¿Cuál es el mejor regalo que has dado?',
        '¿Qué canción te recuerda un momento especial?',
        '¿Cuál fue la decisión más valiente que tomaste?',
        '¿Recuerdas tu primer día en un trabajo nuevo?',
        '¿Cuál fue la lección más dura que aprendiste?',
        '¿Hay un lugar que te traiga mucha nostalgia?',
        '¿Cuál fue la primera película que te hizo llorar?',
        '¿Cuál es tu tradición familiar favorita?',
        '¿Recuerdas un momento de pura felicidad inesperada?',
        '¿Cuál ha sido tu aventura más loca?',
        '¿Qué momento compartido con amigos nunca olvidarás?',
        '¿Cuál fue tu primer gran fracaso y qué aprendiste?',
        '¿Recuerdas la primera vez que te sentiste adulto?',
        '¿Cuál es tu recuerdo favorito de un atardecer?',
        '¿Hay una conversación que haya cambiado tu perspectiva?',
        '¿Cuál fue el momento más emocionante de tu vida?',
        '¿Recuerdas la última vez que reíste hasta llorar?',
        '¿Qué foto guardarías si solo pudieras quedarte con una?',
        '¿Qué persona ya no está pero influyó mucho en ti?',
        '¿Cuál es tu recuerdo más antiguo?',
        '¿Recuerdas un sueño de la infancia que se cumplió?',
        '¿Cuál fue tu mayor acto de rebeldía?',
        '¿Hay un momento que desearías poder revivir?',
        '¿Cuál fue la mejor etapa de tu vida hasta ahora?',
        '¿Recuerdas el primer lugar al que viajaste solo?',
        '¿Qué objeto antiguo conservas y por qué?',
        '¿Cuál fue la mejor fiesta a la que fuiste?',
        '¿Hay un profesor o mentor que cambió tu vida?',
    ],
    humor: [
        '¿Cuál es tu chiste favorito?',
        '¿Qué tipo de comedia prefieres?',
        '¿Te ríes de ti mismo fácilmente?',
        '¿Cuál es la broma más pesada que has hecho?',
        '¿Y la que te han hecho a ti?',
        '¿Qué te parece gracioso que a otros no?',
        '¿Tienes alguna frase o muletilla que repites?',
        '¿Cuál es tu meme favorito?',
        '¿Qué película o serie te hace reír siempre?',
        '¿Te gusta el humor negro?',
        '¿Cuál fue la situación más absurda que viviste?',
        '¿Tienes un comediante favorito?',
        '¿Cómo usas el humor en momentos difíciles?',
        '¿Qué es lo más tonto que has hecho por diversión?',
        '¿Cuál es tu respuesta sarcástica favorita?',
        '¿Cuál es la anécdota que siempre cuentas en reuniones?',
        '¿Prefieres humor sutil o payasadas?',
        '¿Te han dicho que eres gracioso?',
        '¿Cuál es el video más gracioso que has visto?',
        '¿Tienes un apodo gracioso?',
        '¿Cuál fue el malentendido más gracioso que tuviste?',
        '¿Qué te causa risa nerviosa?',
        '¿Cuál es tu expresión facial favorita para hacer reír?',
        '¿Te gusta imitar a alguien? ¿A quién?',
        '¿Cuál fue la metida de pata más graciosa que cometiste?',
        '¿Tienes un ritual gracioso que haces solo?',
        '¿Cuál es la pregunta más absurda que te han hecho?',
        '¿Qué animal crees que serías y por qué?',
        '¿Cuál es tu reacción cuando alguien cuenta un mal chiste?',
        '¿Cuál es la excusa más creativa que inventaste?',
        '¿Cuál es la cosa más random que coleccionas o haces?',
        '¿Qué harías si fueras invisible por un día?',
        '¿Cuál es tu superpoder inútil?',
        '¿Qué frase cliché te molesta pero usas igual?',
        '¿Cuál es tu talento escondido más ridículo?',
        '¿Hay algo que solo tú encuentras gracioso?',
        '¿Cuál es la broma interna que tienes con alguien?',
        '¿Cuál fue tu peor intento de cocinar?',
        '¿Qué harías con un millón de pesos pero tienes que gastarlo en un día?',
        '¿Cuál es el sueño más raro que has tenido?',
        '¿Qué es lo más gracioso que ha hecho tu mascota?',
        '¿Te ríes en momentos inapropiados?',
        '¿Cuál fue la autocorrección del celular más graciosa que te pasó?',
        '¿Cuál es tu reacción al ver tu propia foto de hace 10 años?',
        '¿Hay algún tema del que podrías hablar horas con humor?',
        '¿Cuál es tu forma de hacer reír a alguien triste?',
        '¿Qué canción te pone de buen humor siempre?',
        '¿Cuál es tu peor habilidad y cómo la conviertes en algo gracioso?',
        '¿Cuál fue tu momento más torpe?',
        '¿Tienes algún baile ridículo que solo haces en tu casa?',
    ],
    habitos: [
        '¿Cómo es tu mañana ideal?',
        '¿Qué es lo primero que haces al despertar?',
        '¿Y lo último antes de dormir?',
        '¿Qué comes cuando necesitas comfort food?',
        '¿Cómo tomas tu café o té?',
        '¿Tienes algún ritual diario?',
        '¿Cuántas horas duermes normalmente?',
        '¿Haces ejercicio? ¿Qué tipo?',
        '¿Qué app del celular usas más?',
        '¿Cómo organizas tu espacio de trabajo?',
        '¿Eres ordenado o desordenado?',
        '¿Cocinas o pides comida?',
        '¿Cuál es tu snack favorito?',
        '¿Escuchas música mientras trabajas?',
        '¿Cada cuánto revisas el celular?',
        '¿Prefieres leer o ver series?',
        '¿Cuál es tu playlist del momento?',
        '¿Tienes un lugar favorito en tu casa?',
        '¿Cómo gastas tu tiempo libre?',
        '¿Eres puntual o llegas tarde?',
        '¿Cómo manejas el estrés?',
        '¿Cuál es tu bebida favorita?',
        '¿Prefieres ducharte de mañana o de noche?',
        '¿Tienes alguna superstición?',
        '¿Qué haces cuando no puedes dormir?',
        '¿Planificas tus comidas o improvisas?',
        '¿Cuántas tazas de café tomas al día?',
        '¿Eres de hacer listas?',
        '¿Cómo te relajas después de un día largo?',
        '¿Prefieres ir a un restaurant o cocinar en casa?',
        '¿Cuál es tu deporte favorito para ver?',
        '¿Y para practicar?',
        '¿Tienes algún hobby que nadie sabe?',
        '¿Cómo celebras tu cumpleaños normalmente?',
        '¿Cada cuánto sales con amigos?',
        '¿Prefieres compras online o en tienda?',
        '¿Cómo te gusta viajar: avión, auto, tren?',
        '¿Tienes una rutina de skincare?',
        '¿Prefieres textos largos o mensajes cortos?',
        '¿Eres de los que deja todo para último momento?',
        '¿Cómo te informas: redes, TV, diarios?',
        '¿Escuchas podcasts? ¿De qué tema?',
        '¿Con qué frecuencia lees un libro?',
        '¿Prefieres papel o digital?',
        '¿Cuál es tu guilty pleasure?',
        '¿Cómo te vistes un día normal?',
        '¿Eres de los que ahorra o gasta todo?',
        '¿Cuál es tu lugar favorito para pensar?',
        '¿Qué haces los domingos?',
        '¿Tienes una canción o podcast de alarma favorito?',
    ],
    opiniones: [
        '¿Qué opinas de las redes sociales?',
        '¿Crees en la inteligencia artificial?',
        '¿Qué piensas del cambio climático?',
        '¿Qué opinas del sistema educativo actual?',
        '¿Crees que la tecnología nos acerca o nos aleja?',
        '¿Qué opinas del trabajo remoto?',
        '¿Crees en el matrimonio?',
        '¿Qué piensas sobre tener hijos?',
        '¿Cuál es tu postura sobre las mascotas?',
        '¿Qué opinas de la moda rápida?',
        '¿Crees que la suerte existe?',
        '¿Qué piensas del veganismo?',
        '¿Crees en vida extraterrestre?',
        '¿Qué opinas del sistema de salud?',
        '¿Crees que la universidad es necesaria?',
        '¿Qué piensas de las criptomonedas?',
        '¿Crees en el destino?',
        '¿Qué opinas de los tatuajes?',
        '¿Qué piensas de vivir en el campo vs la ciudad?',
        '¿Crees que la gente es buena por natura?',
        '¿Qué opinas del minimalismo?',
        '¿Crees que el arte tiene valor en la sociedad moderna?',
        '¿Qué piensas de los influencers?',
        '¿Crees que la música actual es peor que la de antes?',
        '¿Qué opinas de la cultura de la cancelación?',
        '¿Crees que debería haber servicio militar obligatorio?',
        '¿Qué piensas del teletrabajo vs presencial?',
        '¿Crees que la igualdad total es posible?',
        '¿Qué opinas de la globalización?',
        '¿Crees que la felicidad se construye o se encuentra?',
        '¿Qué opinas de las dietas extremas?',
        '¿Crees que deberían existir los zoológicos?',
        '¿Qué piensas de las tradiciones?',
        '¿Crees que leer ficción es útil?',
        '¿Qué opinas de la jubilación anticipada?',
        '¿Crees que la historia se repite?',
        '¿Qué piensas de la censura?',
        '¿Crees en la astrología?',
        '¿Qué opinas de las bodas grandes vs íntimas?',
        '¿Crees que debería existir la pena de muerte?',
        '¿Qué piensas de la era digital en la educación?',
        '¿Crees que la democracia funciona?',
        '¿Qué opinas sobre adoptar vs tener hijos biológicos?',
        '¿Crees que la ciencia puede explicarlo todo?',
        '¿Qué piensas del balance vida-trabajo?',
        '¿Qué opinas de los deportes electrónicos?',
        '¿Crees que la automatización quitará empleos?',
        '¿Qué piensas del turismo masivo?',
        '¿Crees que la privacidad ha muerto?',
        '¿Qué opinas del concepto de patria?',
    ],
    relaciones: [
        '¿Qué buscas en una amistad?',
        '¿Cómo demuestras amor?',
        '¿Qué es lo más importante en una pareja?',
        '¿Cuál ha sido tu relación más significativa?',
        '¿Qué aprendiste de una ruptura?',
        '¿Cómo manejas los conflictos con seres queridos?',
        '¿Eres celoso?',
        '¿Qué tan importante es la comunicación?',
        '¿Cómo es tu relación con tus padres?',
        '¿Tienes un mejor amigo? ¿Cómo es?',
        '¿Qué te molesta más en una relación?',
        '¿Crees en el amor a primera vista?',
        '¿Qué consejo de relación darías?',
        '¿Cómo mantienes las amistades a larga distancia?',
        '¿Qué tan rápido confías en alguien nuevo?',
        '¿Prefieres muchos amigos o pocos pero cercanos?',
        '¿Cómo reaccionas cuando un amigo te decepciona?',
        '¿Qué haces para mantener viva una relación?',
        '¿Qué significa para ti la independencia en una relación?',
        '¿Cómo es tu cita ideal?',
        '¿Qué red flag no perdonas?',
        '¿Cómo te llevas con tus hermanos?',
        '¿Qué rol juegas en tu grupo de amigos?',
        '¿Has perdonado una traición?',
        '¿Cómo celebras los logros de tus seres queridos?',
        '¿Qué haces cuando un amigo está pasándola mal?',
        '¿Crees en la amistad entre hombres y mujeres?',
        '¿Cuál fue la pelea más grande que tuviste con alguien?',
        '¿Cómo demuestras gratitud a las personas?',
        '¿Has cortado una amistad? ¿Por qué?',
        '¿Qué tan importante es compartir hobbies con tu pareja?',
        '¿Cómo es tu relación con tus vecinos?',
        '¿Crees que las amistades de la infancia son las más fuertes?',
        '¿Qué opinas de las relaciones a distancia?',
        '¿Cómo manejas las diferencias de opinión?',
        '¿Has tenido un mentor importante?',
        '¿Qué tan importante es la intimidad emocional?',
        '¿Prefieres resolver conflictos hablando o dejando enfriar?',
        '¿Qué harías por tu mejor amigo sin pensarlo?',
        '¿Cuál es tu lenguaje del amor?',
        '¿Cómo apoyas a alguien en duelo?',
        '¿Qué cualidad admiras en tu pareja o pareja ideal?',
        '¿Has tenido una amistad tóxica? ¿Qué aprendiste?',
        '¿Qué significa la lealtad en una amistad?',
        '¿Cómo presentas a alguien que es importante para ti?',
        '¿Prefieres salir en grupo o de a dos?',
        '¿Qué tan importante es el contacto físico?',
        '¿Cómo reaccionas cuando alguien te dice "te quiero"?',
        '¿Qué harías si tu mejor amigo y tu pareja no se llevan bien?',
        '¿Cómo imaginas tu vida social en 10 años?',
    ],
    suenos: [
        '¿Qué querías ser de niño?',
        '¿Cuál es tu sueño más grande ahora?',
        '¿Dónde te ves en 5 años?',
        '¿Si pudieras vivir en cualquier país, cuál sería?',
        '¿Qué harías si no tuvieras miedo?',
        '¿Cuál es tu meta para este año?',
        '¿Tienes un bucket list?',
        '¿Qué carrera estudiarías si empezaras de nuevo?',
        '¿Cuál es tu proyecto soñado?',
        '¿Si tuvieras todo el dinero del mundo, qué harías?',
        '¿Qué quieres lograr antes de los 50?',
        '¿Qué lugar del mundo quieres conocer?',
        '¿Qué habilidad te gustaría dominar?',
        '¿Cuál es tu sueño secreto?',
        '¿Qué legado quieres dejar al mundo?',
        '¿Si pudieras hacer cualquier cosa mañana, qué harías?',
        '¿Qué hobby siempre quisiste empezar?',
        '¿Dónde sería tu casa soñada?',
        '¿Sueñas con escribir un libro? ¿De qué trataría?',
        '¿Qué instrumento te gustaría aprender?',
        '¿Si pudieras cenar con cualquier persona, viva o muerta, quién sería?',
        '¿Cuál es tu fantasía de emprendimiento?',
        '¿Qué cambiarías del mundo si pudieras?',
        '¿Sueñas con algo que parece inalcanzable?',
        '¿Qué te falta para sentirte realizado?',
        '¿Cuál sería tu día perfecto?',
        '¿Qué experiencia extrema te gustaría vivir?',
        '¿Si pudieras viajar en el tiempo, a qué época irías?',
        '¿Qué invento te gustaría crear?',
        '¿Cuál sería tu retiro ideal?',
        '¿Quieres aprender otro idioma? ¿Cuál?',
        '¿Si pudieras tener cualquier mascota, cuál sería?',
        '¿Qué curso o taller te gustaría tomar?',
        '¿Sueñas con la fama? ¿En qué campo?',
        '¿Cuál sería tu aporte ideal a la humanidad?',
        '¿Si pudieras resolver un problema mundial, cuál sería?',
        '¿Qué tipo de voluntariado te gustaría hacer?',
        '¿Dónde quieres estar cuando seas anciano?',
        '¿Qué aventura pendiente tienes?',
        '¿Si pudieras vivir una semana como otra persona, quién sería?',
        '¿Cuál es tu meta de salud?',
        '¿Qué tipo de negocio abrirías?',
        '¿Si pudieras dominar un deporte, cuál sería?',
        '¿Qué tradición nueva te gustaría crear?',
        '¿Cuál es la cosa más loca que quieres hacer algún día?',
        '¿Si pudieras garantizar un solo resultado en tu vida, cuál sería?',
        '¿Qué tipo de casa construirías si no hubiera límites?',
        '¿Sueñas con un año sabático? ¿Qué harías?',
        '¿Hay algo que prometiste hacer y aún no has hecho?',
        '¿Cuál sería tu epitafio ideal?',
    ],
    filosofia: [
        '¿Cuál crees que es el sentido de la vida?',
        '¿Crees que todo pasa por algo?',
        '¿Qué piensas que hay después de la muerte?',
        '¿Crees en el libre albedrío?',
        '¿Qué significa ser feliz?',
        '¿Crees que el sufrimiento tiene propósito?',
        '¿Qué nos hace humanos?',
        '¿Crees que la vida es justa?',
        '¿Qué peso tiene el pasado en nuestras decisiones?',
        '¿Es posible conocerse completamente a uno mismo?',
        '¿Crees que existe la verdad objetiva?',
        '¿Qué tan importante es el tiempo?',
        '¿Prefieres saber la fecha de tu muerte o no?',
        '¿Crees que la conciencia es única del ser humano?',
        '¿Qué te parece más valioso: la experiencia o el conocimiento?',
        '¿Crees que somos producto de nuestras circunstancias?',
        '¿Qué opinas de la soledad?',
        '¿Crees que el universo tiene un propósito?',
        '¿Es mejor haber amado y perdido que nunca haber amado?',
        '¿Qué defines como "real"?',
        '¿Crees que podemos cambiar el mundo?',
        '¿Qué tan importante es dejar huella?',
        '¿Prefieres una vida larga y tranquila o corta e intensa?',
        '¿Crees que la moralidad es relativa?',
        '¿Qué significa ser libre?',
        '¿Crees que el arte imita la vida o al revés?',
        '¿Qué papel juega el azar en nuestras vidas?',
        '¿Crees que la inteligencia es más importante que la bondad?',
        '¿Qué piensas que nos espera como civilización?',
        '¿Es posible la paz mundial?',
        '¿Crees que los animales tienen alma?',
        '¿Qué tan real es el concepto de "normal"?',
        '¿Crees que vivimos en una simulación?',
        '¿Qué opinas de la inmortalidad?',
        '¿Crees que el progreso siempre es positivo?',
        '¿Qué significa madurar?',
        '¿Crees que la nostalgia es buena o mala?',
        '¿Qué tan importante es la muerte para darle sentido a la vida?',
        '¿Crees que somos nuestra memoria?',
        '¿Qué piensas de la idea de "destino"?',
        '¿Crees que la tecnología puede reemplazar las relaciones humanas?',
        '¿Qué opinas de la idea de múltiples vidas?',
        '¿Crees que nacemos con un propósito?',
        '¿Qué es más importante: la razón o el corazón?',
        '¿Crees que el lenguaje limita nuestro pensamiento?',
        '¿Qué significa envejecer con gracia?',
        '¿Crees que la felicidad es una decisión?',
        '¿Qué piensas del silencio?',
        '¿Crees que todos tenemos un lado oscuro?',
        '¿Qué es lo que hace que un momento sea memorable?',
    ],
    gustos: [
        '¿Cuál es tu comida favorita?',
        '¿Tu película favorita?',
        '¿Tu canción favorita?',
        '¿Tu libro favorito?',
        '¿Tu color favorito?',
        '¿Tu estación del año favorita?',
        '¿Playa o montaña?',
        '¿Perros o gatos?',
        '¿Dulce o salado?',
        '¿Qué género musical prefieres?',
        '¿Serie favorita de todos los tiempos?',
        '¿Tu artista o banda favorita?',
        '¿Qué tipo de comida no soportas?',
        '¿Cuál es tu deporte favorito?',
        '¿Prefieres frío o calor?',
        '¿Vino, cerveza o tragos?',
        '¿Cuál es tu postre favorito?',
        '¿Tu videojuego favorito?',
        '¿Prefieres la ciudad o el campo?',
        '¿Cuál es tu red social favorita?',
        '¿Pizza o hamburguesa?',
        '¿Cuál es tu estilo de música para relajarte?',
        '¿Prefieres el cine o ver pelis en casa?',
        '¿Cuál es tu restaurante favorito?',
        '¿Helado favorito?',
        '¿Prefieres lluvia o sol?',
        '¿Cuál es tu hobbie principal?',
        '¿Prefieres comedia, drama o acción?',
        '¿Cuál es tu marca favorita de ropa?',
        '¿Tu olor favorito?',
        '¿Prefieres sushi o tacos?',
        '¿Cuál es tu hora favorita del día?',
        '¿Prefieres el mar o la piscina?',
        '¿Cuál es tu emoji más usado?',
        '¿Prefieres conciertos o festivales?',
        '¿Tu juego de mesa favorito?',
        '¿Prefieres documentales o ficción?',
        '¿Cuál es tu país favorito que has visitado?',
        '¿Prefieres rol romántico o de aventura en películas?',
        '¿Tu aplicación favorita?',
        '¿Prefieres la radio o el podcast?',
        '¿Cuál es tu flor favorita?',
        '¿Prefieres el amanecer o el atardecer?',
        '¿Cuál es tu superhéroe o personaje ficticio favorito?',
        '¿Prefieres algo clásico o moderno en decoración?',
        '¿Cuál es tu forma favorita de viajar?',
        '¿Prefieres dulce de leche o chocolate?',
        '¿Cuál es tu receta favorita?',
        '¿Prefieres un lago o un río?',
        '¿Cuál es tu palabra favorita?',
    ],
    identidad: [
        '¿Cómo te presentarías ante un desconocido?',
        '¿Qué te define como persona?',
        '¿De qué estás más orgulloso?',
        '¿Qué parte de ti quieres que la gente recuerde?',
        '¿Cómo ha cambiado tu personalidad con los años?',
        '¿Qué te hace sentir vivo?',
        '¿Cuál es tu propósito en la vida?',
        '¿Qué rol juegas en la vida de otros?',
        '¿Cómo te ves a ti mismo vs cómo te ven los demás?',
        '¿Qué aspecto de tu identidad es más importante?',
        '¿Qué harías si no te juzgaran?',
        '¿Te identificas más con tu trabajo o tus hobbies?',
        '¿Tu nacionalidad es importante para tu identidad?',
        '¿Qué significa tu nombre? ¿Te gusta?',
        '¿Cómo influye tu cultura en quién eres?',
        '¿Qué generación sientes que define tu forma de ver el mundo?',
        '¿Cuál es la etapa de tu vida que más te formó?',
        '¿Hay algo de ti que nadie sabe?',
        '¿Cómo manejas las expectativas de los demás sobre ti?',
        '¿Sientes que eres quien quieres ser?',
        '¿Qué parte de ti viene de tu familia?',
        '¿Qué parte de ti construiste solo?',
        '¿Cómo describirías tu voz interior?',
        '¿Qué máscara usas con el mundo?',
        '¿Quién eras hace 10 años vs quién eres ahora?',
        '¿Hay algo que quisieras que la gente entendiera de ti?',
        '¿Qué te hace sentir auténtico?',
        '¿Cuál es tu mayor contradicción?',
        '¿Cómo reaccionas cuando alguien malinterpreta quién eres?',
        '¿Qué serías sin tus recuerdos?',
        '¿Te importa el legado que dejas?',
        '¿Qué frase te describe mejor?',
        '¿Cuál es la cosa más personal que podrías compartir?',
        '¿Qué pregunta te gustaría que te hicieran?',
        '¿Hay una canción que sientas que es "tu canción"?',
        '¿Cómo te gustaría que te recordaran?',
        '¿Qué foto tuya representa mejor quién eres?',
        '¿Si fueras un personaje de ficción, quién serías?',
        '¿Cuál es tu grito de guerra personal?',
        '¿Qué tatuaje te pondrías que represente tu esencia?',
        '¿Cuál es tu mantra o lema de vida?',
        '¿Si pudieras grabar un mensaje para el futuro, qué dirías?',
        '¿Qué quieres que digan de ti cuando no estés?',
        '¿Cuál es la verdad más profunda que conoces sobre ti?',
        '¿Te sientes en paz con quién eres?',
        '¿Qué versión de ti mismo quieres preservar?',
        '¿Hay algo que nunca vas a cambiar de ti?',
        '¿Cuál es tu mayor misterio personal?',
        '¿Si tuvieras que resumir tu vida en una frase, cuál sería?',
        '¿Qué te gustaría decirle al mundo?',
    ],
};

// Flatten into indexed questions with auto-assigned depth
let id = 0;
export const QUESTIONS: Question[] = Object.entries(raw).flatMap(
    ([category, texts]) =>
        texts.map((text, i) => {
            const ratio = i / texts.length;
            const depth: 'basic' | 'deep' | 'expert' =
                ratio < 0.4 ? 'basic' : ratio < 0.75 ? 'deep' : 'expert';
            return { id: id++, category, text, depth };
        }),
);

export const CATEGORIES = Object.keys(raw);
export const TOTAL_QUESTIONS = QUESTIONS.length;
export const MIN_QUESTIONS = 25;
