export const MIN_ENROLLMENT_INTERACTIONS = 50;
export const MIN_COVERAGE_PER_CATEGORY = 5;
export const MAX_VOICE_SAMPLE_SIZE_MB = 50;
export const MAX_AVATAR_IMAGE_SIZE_MB = 10;
export const SUPPORTED_AUDIO_FORMATS = ['audio/webm', 'audio/wav', 'audio/mp3', 'audio/ogg'];
export const SUPPORTED_IMAGE_FORMATS = ['image/jpeg', 'image/png', 'image/webp'];

export const SIMULATION_DISCLAIMER =
  'This is a simulation. This is not a real person. Responses are generated by AI based on a cognitive profile.';

export const SKIN_COLORS: Record<string, string> = {
  default: '#6B7280',
  hoodie: '#1F2937',
  suit: '#111827',
  casual: '#059669',
  dark: '#18181B',
  neon: '#7C3AED',
};

export const MOOD_EMOJIS: Record<string, string> = {
  neutral: '😐',
  happy: '😊',
  serious: '😤',
  angry: '😠',
  sad: '😢',
  excited: '🤩',
};

export const CATEGORY_LABELS: Record<string, string> = {
  LINGUISTIC: 'Language Style',
  LOGICAL: 'Logical Reasoning',
  MORAL: 'Moral Framework',
  VALUES: 'Core Values',
  ASPIRATIONS: 'Dreams & Goals',
  PREFERENCES: 'Preferences',
  AUTOBIOGRAPHICAL: 'Life Story',
  EMOTIONAL: 'Emotional World',
};

export const CATEGORY_DESCRIPTIONS: Record<string, string> = {
  LINGUISTIC: 'How you express yourself, your word choices, communication patterns',
  LOGICAL: 'How you reason through problems and make decisions',
  MORAL: 'Your ethical framework and moral principles',
  VALUES: 'What matters most to you and what you stand for',
  ASPIRATIONS: 'Your dreams, goals, and vision for the future',
  PREFERENCES: 'Your likes, dislikes, tastes, and habits',
  AUTOBIOGRAPHICAL: 'Key moments and experiences that shaped you',
  EMOTIONAL: 'How you experience and express emotions',
};
